name: GameCI

on:
  push: {}
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      fail-fast: false
      matrix:
        repos:
          - |
            https://vpm.nadena.dev/vpm.json
            https://vpm.narazaka.net/index.json
        include:
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.1.1
            vrcsdk-avatars: 3.1.9
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.1.1
            vrcsdk-avatars: 3.2.0
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.1.1
            vrcsdk-avatars: 3.4.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.5.1
            vrcsdk-avatars: 3.2.0
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.5.1
            vrcsdk-avatars: 3.4.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.7.7
            vrcsdk-avatars: 3.2.0
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.7.7
            vrcsdk-avatars: 3.4.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.8.4
            vrcsdk-avatars: 3.2.0
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.8.4
            vrcsdk-avatars: 3.4.2
          - unity: 2022.3.6f1
            packages: nadena.dev.modular-avatar 1.8.4
            vrcsdk-avatars: 3.5.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.9.2
            vrcsdk-avatars: 3.2.0
          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.9.2
            vrcsdk-avatars: 3.4.2
          - unity: 2022.3.6f1
            packages: nadena.dev.modular-avatar 1.9.2
            vrcsdk-avatars: 3.5.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.9.8
            vrcsdk-avatars: 3.4.2
          - unity: 2022.3.6f1
            packages: nadena.dev.modular-avatar 1.9.8
            vrcsdk-avatars: 3.5.2

          - unity: 2019.4.31f1
            packages: nadena.dev.modular-avatar 1.9.12
            vrcsdk-avatars: 3.4.2
          - unity: 2022.3.6f1
            packages: nadena.dev.modular-avatar 1.9.12
            vrcsdk-avatars: 3.5.2
    steps:
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: vrchat-community/template-avatar

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: TargetPackage

      - name: get packageName
        id: packageName
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
          path: "TargetPackage/package.json"
          prop_path: "name"

      - name: Place package
        run: |
          mv TargetPackage Packages/${{ steps.packageName.outputs.prop }}

      - name: Setup Project
        run: |
          cp -R Packages/net.narazaka.vrchat.avatar-menu-creater-for-ma/.github/workflows/ProjectRoot/${{ matrix.unity }}/* .
          rm -rf Packages/com.vrchat.core.bootstrap

      - name: Setup vrc-get
        uses: anatawa12/sh-actions/setup-vrc-get@master

      - name: Add VPM repositories
        shell: bash
        env:
          REPOS: ${{ matrix.repos }}
        run: |
          printf '%s\n' "$REPOS" | while IFS= read -r url; do
            if [ -n "${url:-}" ]; then
              echo "vrc-get repo add -- \"$url\"" >&2
              vrc-get repo add -- "$url"
            fi
          done

      - name: Resolve VPM packages
        shell: bash
        env:
          PACKAGES: ${{ matrix.packages }}
        run: |
          if [ -n "${{ matrix.vrcsdk-avatars }}" ] ; then
            vrc-get install --yes com.vrchat.avatars ${{ matrix.vrcsdk-avatars }}
          fi
          if [ -n "${{ matrix.vrcsdk-worlds }}" ] ; then
            vrc-get install --yes com.vrchat.worlds ${{ matrix.vrcsdk-worlds }}
          fi
          printf '%s\n' "$PACKAGES" | while IFS= read -r p; do
            if [ -n "${p:-}" ]; then
              echo "vrc-get install --yes $p" >&2
              vrc-get install --yes $p
            fi
          done

      - uses: anatawa12/sh-actions/resolve-vpm-packages@master

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-unity=${{ matrix.unity }}-ma=${{ matrix.ma }}-vrcsdk=${{ matrix.vrcsdk }}
          restore-keys: Library-unity=${{ matrix.unity }}-ma=${{ matrix.ma }}-vrcsdk=${{ matrix.vrcsdk }}

      # Test
      - name: Run tests
        id: gameci
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
          customParameters: -nographics -assemblyNames AvatarMenuCreatorForMA.Test
          checkName: Test Unity=${{ matrix.unity }} MA=${{ matrix.ma }} VRCSDK=${{ matrix.vrcsdk }}
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+AvatarMenuCreatorForMA.*,-AvatarMenuCreatorForMA.Test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Unity=${{ matrix.unity }} MA=${{ matrix.ma }} VRCSDK=${{ matrix.vrcsdk }}
          path: ${{ steps.gameci.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage Unity=${{ matrix.unity }} MA=${{ matrix.ma }} VRCSDK=${{ matrix.vrcsdk }}
          path: ${{ steps.gameci.outputs.coveragePath }}
