name: GameCI

on:
  push: {}
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  call-build-listing:
    needs: release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: Narazaka/vpm-repos/.github/workflows/call-build-listing.yml@main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
    with:
      repo: AvatarMenuCreaterForMA
      ref: master

  release:
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    uses: Narazaka/vpm-repos/.github/workflows/release.yml@main
    with:
      ma: true

  test:
    uses: Narazaka/vpm-repos/.github/workflows/gameci.yml@main
    permissions:
      checks: write
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      unity: ${{ matrix.unity }}
      vrcsdk-type: avatars
      vrcsdk-version: ${{ matrix.vrcsdk-version }}
      repos: |
        https://vpm.nadena.dev/vpm.json
        https://vpm.narazaka.net/index.json
      packages: |
        nadena.dev.modular-avatar ${{ matrix.ma }}
        ${{ matrix.additional_packages }}
      name: MA=${{ matrix.ma }}${{ matrix.additional_name }}
      assemblyNames: AvatarMenuCreatorForMA.Test
      assemblyFilters: +AvatarMenuCreatorForMA.*,-AvatarMenuCreatorForMA.Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - unity: 2019.4.31f1
            ma: 1.1.1
            vrcsdk-version: 3.1.9
          - unity: 2019.4.31f1
            ma: 1.1.1
            vrcsdk-version: 3.2.0
          - unity: 2019.4.31f1
            ma: 1.1.1
            vrcsdk-version: 3.4.2

          - unity: 2019.4.31f1
            ma: 1.5.1
            vrcsdk-version: 3.2.0
          - unity: 2019.4.31f1
            ma: 1.5.1
            vrcsdk-version: 3.4.2

          - unity: 2019.4.31f1
            ma: 1.7.7
            vrcsdk-version: 3.2.0
          - unity: 2019.4.31f1
            ma: 1.7.7
            vrcsdk-version: 3.4.2

          - unity: 2019.4.31f1
            ma: 1.8.4
            vrcsdk-version: 3.2.0
          - unity: 2019.4.31f1
            ma: 1.8.4
            vrcsdk-version: 3.4.2
          - unity: 2022.3.6f1
            ma: 1.8.4
            vrcsdk-version: 3.5.2

          - unity: 2019.4.31f1
            ma: 1.9.2
            vrcsdk-version: 3.2.0
          - unity: 2019.4.31f1
            ma: 1.9.2
            vrcsdk-version: 3.4.2
          - unity: 2022.3.6f1
            ma: 1.9.2
            vrcsdk-version: 3.5.2

          - unity: 2019.4.31f1
            ma: 1.9.8
            additional_packages: nadena.dev.ndmf 1.3.7
            vrcsdk-version: 3.4.2
          - unity: 2022.3.6f1
            ma: 1.9.8
            additional_packages: nadena.dev.ndmf 1.3.7
            vrcsdk-version: 3.5.2

          # ndmf>=1.4.0 ProvidedParameter
          - unity: 2019.4.31f1
            ma: 1.9.13
            additional_packages: nadena.dev.ndmf 1.4.1
            vrcsdk-version: 3.4.2
          - unity: 2022.3.6f1
            ma: 1.9.13
            additional_packages: nadena.dev.ndmf 1.4.1
            vrcsdk-version: 3.5.2
            
          - unity: 2022.3.22f1
            ma: 1.10.11
            # ndmf>=1.5 ProvidedParameter.DefaultValue
            vrcsdk-version: 3.5.2
          - unity: 2022.3.22f1
            ma: 1.10.11
            additional_packages: net.narazaka.vrchat.compressed-int-parameters 1.0.0
            additional_name: " CompressedIntParameters=1.0.0"
            vrcsdk-version: 3.5.2
